# Generated by Django 5.1.3 on 2024-12-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('נקבה', 'נקבה'), ('אחר', 'אחר'), ('זכר', 'זכר')], max_length=4, null=True),
        ),
    ]
