# Generated by Django 5.1.3 on 2024-12-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('אחר', 'אחר'), ('זכר', 'זכר'), ('נקבה', 'נקבה')], max_length=4, null=True),
        ),
    ]
