# Generated by Django 5.1.3 on 2024-12-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_rename_price_activity_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ai_suggestion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
