# Generated by Django 5.1.3 on 2024-12-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_alter_activity_options_activity_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='company',
            field=models.CharField(blank=True, default='alone', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
