# Generated by Django 5.1.3 on 2024-12-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_alter_activity_company_alter_activity_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='company',
            field=models.CharField(blank=True, default='myself', max_length=255, null=True),
        ),
    ]
