# Generated by Django 5.1.3 on 2024-12-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0009_alter_activity_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('WATCH_MOVIE', 'Watching a Movie'), ('PLAY_GAME', 'Playing a Game'), ('DINING_OUT', 'Dining Out'), ('WINE', 'Wine'), ('PARTY', 'Party'), ('BOWLING', 'bowling')], help_text='The type of activity.', max_length=20),
        ),
    ]
