# Generated by Django 5.1.3 on 2024-12-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_remove_activity_latitude_remove_activity_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.DateTimeField(max_length=20),
        ),
    ]
