# Generated by Django 5.1.3 on 2024-12-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_alter_activity_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='favorite_activities',
            new_name='favorite_places',
        ),
    ]
