# Generated by Django 5.1.3 on 2025-01-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ai_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('נקבה', 'נקבה'), ('אחר', 'אחר'), ('זכר', 'זכר')], max_length=4, null=True),
        ),
    ]
