# Generated by Django 5.1.3 on 2025-01-10 15:44

import authenticate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0012_alter_activity_ai_suggestion_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='assets/default_profile_picture.jpg', null=True, upload_to=authenticate.models.profile_picture_upload_path),
        ),
    ]
