# Generated by Django 5.1.3 on 2024-12-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0012_rename_favorite_activities_customuser_favorite_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('לצפות בסרט', 'לצפות בסרט'), ('לשחק', 'לשחק'), ('מסעדה', 'מסעדה'), ('יין', 'יין'), ('מסיבה', 'מסיבה'), ('באולינג', 'באולינג')], help_text='The type of activity.', max_length=20),
        ),
    ]
