# Generated by Django 5.1.3 on 2024-12-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0013_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='search_friends',
            field=models.BooleanField(default=False),
        ),
    ]
