# Generated by Django 5.1.3 on 2024-12-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0015_customuser_latitude_customuser_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('זכר', 'זכר'), ('אחר', 'אחר'), ('נקבה', 'נקבה')], max_length=4, null=True),
        ),
    ]
