# Generated by Django 5.1.3 on 2024-12-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0016_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('נקבה', 'נקבה'), ('זכר', 'זכר'), ('אחר', 'אחר')], max_length=4, null=True),
        ),
    ]
