# Generated by Django 5.1.3 on 2024-12-15 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0018_chatroom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='deleted_at',
        ),
    ]
