# Generated by Django 5.1.3 on 2024-12-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0019_remove_chatroom_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('זכר', 'זכר'), ('נקבה', 'נקבה'), ('אחר', 'אחר')], max_length=4, null=True),
        ),
    ]
